apiVersion: v1
items:
- apiVersion: karpenter.k8s.aws/v1
  kind: EC2NodeClass
  metadata:
    annotations:
      karpenter.k8s.aws/ec2nodeclass-hash: "2096614555968838218"
      karpenter.k8s.aws/ec2nodeclass-hash-version: v5
    creationTimestamp: "2026-08-23T20:45:11Z"
    finalizers:
    - karpenter.k8s.aws/termination
    generation: 2
    labels:
      app.kubernetes.io/component: node-class
      app.kubernetes.io/managed-by: terraform
      app.kubernetes.io/name: karpenter
      environment: dev
    name: default
    resourceVersion: "398134"
    uid: eabf29f7-c29c-4bc0-a066-33f511b37ea5
  spec:
    amiFamily: AL2023
    amiSelectorTerms:
    - alias: al2023@latest
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        iops: 3000
        throughput: 125
        volumeSize: 50Gi
        volumeType: gp3
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 1
      httpTokens: required
    role: cloudhusller-commerce-platform-dev-karpenter-node-role
    securityGroupSelectorTerms:
    - id: sg-001313afe67e29162
    subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cloudhusller-commerce-platform-dev-eks
    tags:
      CostCenter: cloudhusller
      Name: cloudhusller-commerce-platform-dev-karpenter-node
      Owner: Gabin
      karpenter.sh/discovery: cloudhusller-commerce-platform-dev-eks
      karpenter.sh/node-class: default
  status:
    amis:
    - id: ami-0527b71651b58fb01
      name: amazon-eks-node-al2023-x86_64-standard-1.33-v20260818
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    - id: ami-061fec6c2409dd092
      name: amazon-eks-node-al2023-arm64-nvidia-1.33-v20260818
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
    - id: ami-0699623f8d4703d42
      name: amazon-eks-node-al2023-x86_64-neuron-1.33-v20260818
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: Exists
    - id: ami-0be1e5f4c277dc963
      name: amazon-eks-node-al2023-x86_64-nvidia-1.33-v20260818
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
    - id: ami-0ce8386da44c8e1c1
      name: amazon-eks-node-al2023-arm64-standard-1.33-v20260818
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    conditions:
    - lastTransitionTime: "2026-08-23T20:45:11Z"
      message: ""
      observedGeneration: 2
      reason: AMIsReady
      status: "True"
      type: AMIsReady
    - lastTransitionTime: "2026-08-23T20:45:11Z"
      message: ""
      observedGeneration: 2
      reason: CapacityReservationsReady
      status: "True"
      type: CapacityReservationsReady
    - lastTransitionTime: "2026-08-23T20:45:11Z"
      message: ""
      observedGeneration: 2
      reason: PlacementGroupReady
      status: "True"
      type: PlacementGroupReady
    - lastTransitionTime: "2026-08-23T20:45:11Z"
      message: ""
      observedGeneration: 2
      reason: SubnetsReady
      status: "True"
      type: SubnetsReady
    - lastTransitionTime: "2026-08-23T20:45:12Z"
      message: ""
      observedGeneration: 2
      reason: InstanceProfileReady
      status: "True"
      type: InstanceProfileReady
    - lastTransitionTime: "2026-08-24T06:12:51Z"
      message: ""
      observedGeneration: 2
      reason: SecurityGroupsReady
      status: "True"
      type: SecurityGroupsReady
    - lastTransitionTime: "2026-08-24T06:12:52Z"
      message: ""
      observedGeneration: 2
      reason: ValidationSucceeded
      status: "True"
      type: ValidationSucceeded
    - lastTransitionTime: "2026-08-24T06:12:52Z"
      message: ""
      observedGeneration: 2
      reason: Ready
      status: "True"
      type: Ready
    instanceProfile: cloudhusller-commerce-platform-dev-eks_16156594160455229137
    securityGroups:
    - id: sg-001313afe67e29162
      name: eks-cluster-sg-cloudhusller-commerce-platform-dev-eks-1721880706
    subnets:
    - id: subnet-05ce23812d015cec0
      zone: us-east-2b
      zoneID: use2-az2
    - id: subnet-0d4c4a7c760bc8e10
      zone: us-east-2a
      zoneID: use2-az1
kind: List
metadata:
  resourceVersion: ""
