###############################################################
# ACM Certificate
###############################################################

output "certificate_id" {
  description = "ID of the ACM certificate."
  value       = aws_acm_certificate.this.id
}

output "certificate_arn" {
  description = "ARN of the ACM certificate."
  value       = aws_acm_certificate.this.arn
}

output "certificate_domain_name" {
  description = "Primary domain name for the ACM certificate."
  value       = aws_acm_certificate.this.domain_name
}

output "certificate_status" {
  description = "Status of the ACM certificate."
  value       = aws_acm_certificate.this.status
}

output "validation_method" {
  description = "Validation method used for the ACM certificate."
  value       = aws_acm_certificate.this.validation_method
}

###############################################################
# Domain Validation Options
###############################################################

output "domain_validation_options" {
  description = "Domain validation options generated by ACM."

  value = {
    for option in aws_acm_certificate.this.domain_validation_options :
    option.domain_name => {
      domain_name           = option.domain_name
      resource_record_name  = option.resource_record_name
      resource_record_type  = option.resource_record_type
      resource_record_value = option.resource_record_value
    }
  }
}

###############################################################
# Route53 Validation Records
###############################################################

output "validation_record_fqdns" {
  description = "FQDNs of Route53 DNS validation records."

  value = [
    for record in aws_route53_record.validation :
    record.fqdn
  ]
}

output "validation_record_names" {
  description = "Names of Route53 DNS validation records."

  value = {
    for name, record in aws_route53_record.validation :
    name => record.name
  }
}

output "validation_record_types" {
  description = "Types of Route53 DNS validation records."

  value = {
    for name, record in aws_route53_record.validation :
    name => record.type
  }
}

output "validation_record_values" {
  description = "Values of Route53 DNS validation records."

  value = {
    for name, record in aws_route53_record.validation :
    name => record.records
  }
}

###############################################################
# ACM Certificate Validation
###############################################################

output "validated_certificate_arn" {
  description = "Validated ACM certificate ARN when Route53 DNS validation is enabled."

  value = try(
    aws_acm_certificate_validation.this[0].certificate_arn,
    null
  )
}