# ========================================================================================
# tells Argo CD to deploy the frontend dev Kustomize overlay from Git into the cloudhusller-dev namespace and continuously reconcile drift.
# ========================================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend-dev
  namespace: argocd

spec:
  project: cloudhusller-dev

  source:
    repoURL: https://github.com/Gabinsime75/CloudHustler-Commerce-Platform.git
    targetRevision: main
    path: gitops/overlays/dev/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudhusller-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

  revisionHistoryLimit: 10