apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../applications/frontend-dev.yaml
  - ../applications/checkoutservice-dev.yaml
  - ../applications/productcatalogservice-dev.yaml
  - ../applications/shippingservice-dev.yaml
  - ../applications/currencyservice-dev.yaml
  - ../applications/paymentservice-dev.yaml
  - ../applications/cartservice-dev.yaml
  - ../applications/redis-cart-dev.yaml
  - ../applications/istio-routing-dev.yaml