apiVersion: v1
kind: Service

metadata:
  name: currencyservice
  labels:
    app: currencyservice
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/part-of: cloudhusller-commerce-platform

spec:
  # Internal-only Kubernetes service.
  type: ClusterIP

  selector:
    app: currencyservice

  ports:
    - name: grpc
      port: 7000
      targetPort: grpc
      protocol: TCP