apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
    app.kubernetes.io/name: cartservice
    app.kubernetes.io/part-of: cloudhusller-commerce-platform

spec:
  type: ClusterIP

  selector:
    app: cartservice

  ports:
    - name: grpc
      port: 7070
      targetPort: grpc
      protocol: TCP