name: Product Catalog Service CI

on:
  push:
    branches:
      - main
    paths:
      - "applications/productcatalogservice/**"
      - ".github/workflows/productcatalogservice-ci.yml"
      - ".github/workflows/reusable-service-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "applications/productcatalogservice/**"
      - ".github/workflows/productcatalogservice-ci.yml"
      - ".github/workflows/reusable-service-ci.yml"

permissions:
  contents: read
  id-token: write

jobs:
  productcatalogservice:
    uses: ./.github/workflows/reusable-service-ci.yml

    with:
      service_name: productcatalogservice
      service_path: applications/productcatalogservice
      runtime: go
      aws_region: us-east-2
      ecr_repository: cloudhusller-commerce-platform-dev/productcatalogservice
      role_to_assume: arn:aws:iam::396913735153:role/cloudhusller-commerce-platform-dev-github-actions-ci

    secrets: inherit